BEGIN;
delete from action where uid=0;
insert into action (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from employe where uid=0;
insert into employe (uid,nom,prenom,codecrea) values (0,'indefini',' ','Makefile');
delete from etat_note where uid=0;
insert into etat_note (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from note where uid=0;
insert into note (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from object where uid=0;
insert into object (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from personne where uid=0;
insert into personne (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from personne_physique where uid=0;
insert into personne_physique (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from societe where uid=0;
insert into societe (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from type where uid=0;
insert into type (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from type_note where uid=0;
insert into type_note (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from type_role where uid=0;
insert into type_role (uid,nom,codecrea) values (0,'indefini','Makefile');
delete from userid where uid=0;
insert into userid (uid,nom,codecrea) values (0,'indefini','Makefile');
COMMIT;
